// Code generated by MockGen. DO NOT EDIT.
// Source: generator/faker.go

// Package mock_generator is a generated GoMock package.
package mock_generator

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ReplaceStringWithFakerWhenRequested mocks base method.
func (m *MockService) ReplaceStringWithFakerWhenRequested(request string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceStringWithFakerWhenRequested", request)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceStringWithFakerWhenRequested indicates an expected call of ReplaceStringWithFakerWhenRequested.
func (mr *MockServiceMockRecorder) ReplaceStringWithFakerWhenRequested(request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceStringWithFakerWhenRequested", reflect.TypeOf((*MockService)(nil).ReplaceStringWithFakerWhenRequested), request)
}
